services:
  typedb:
    image: typedb/typedb:3.11.5
    container_name: kp-typedb
    ports:
      - "1729:1729"
      - "8000:8000"
    restart: unless-stopped
    volumes:
      - kp-typedb:/opt/typedb-all-linux/server/data

  grobid:
    image: grobid/grobid:0.9.0-crf
    container_name: kp-grobid
    ports:
      - "8070:8070"
    restart: unless-stopped

volumes:
  kp-typedb:
